version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: department_student_application_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: secret
    ports:
      - "3303:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3001"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password

volumes:
  db_data: